[tool.black]
line-length = 88
target-version = ["py38", "py310", "py312"]
extend-exclude = '''
(
  /(
      \.git
    | \.venv
    | venv
    | build
    | dist
    | \.eggs
    | .*\.egg-info
  )/
)
'''
