name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*rc*'
      - 'v*beta*'
      - 'v*alpha*'
  workflow_dispatch: {}

jobs:
  build-and-publish-testpypi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install -U pip
          python -m pip install build twine

      - name: Build package
        run: python -m build

      - name: Check metadata
        run: python -m twine check dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

